### ISSUE TITLE
go rpc的版本和etcd的版本问题

### ISSUE THREAD

**Issue by Golong-me** [tal-tech/go-zero#254] opened 2020-12-08 13:11 UTC
在rpc服务中
require (
	github.com/golang/protobuf v1.4.2
        github.com/tal-tech/go-zero v1.0.29
       google.golang.org/grpc v1.34.0     **//最新版报错, v1.29.1版本可以**
	google.golang.org/protobuf v1.25.0
)

**报错如下**
`# go.etcd.io/etcd/clientv3/balancer/picker
..\..\pkg\mod\go.etcd.io\etcd@v0.0.0-20200402134248-51bdeb39e698\clientv3\balancer\picker\err.go:25:9: cannot use &errPicker literal (type *errPicker) as type Picker in return argument:
	***errPicker does not implement Picker (wrong type for Pick method)**
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
..\..\pkg\mod\go.etcd.io\etcd@v0.0.0-20200402134248-51bdeb39e698\clientv3\balancer\picker\roundrobin_balanced.go:33:9: cannot use &rrBalanced literal (type *rrBalanced) as type Picker in return argument:
	*rrBalanced does not implement Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
# github.com/tal-tech/go-zero/zrpc/internal/balancer/p2c
..\..\pkg\mod\github.com\tal-tech\go-zero@v1.0.29\zrpc\internal\balancer\p2c\p2c.go:41:32: not enough arguments in call to base.NewBalancerBuilder
	have (string, *p2cPickerBuilder)
	want (string, base.PickerBuilder, base.Config)
..\..\pkg\mod\github.com\tal-tech\go-zero@v1.0.29\zrpc\internal\balancer\p2c\p2c.go:58:9: cannot use &p2cPicker literal (type *p2cPicker) as type balancer.Picker in return argument:
	*p2cPicker does not implement balancer.Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
`

**Comment by kevwan** [comment] 2020-12-08 14:35
使用grpc 1.29.1

可以用replace指令

这个是etcd和grpc打架的原因，暂无解决方法

**Comment by kevwan** [comment] 2020-12-08 14:42
duplicate of #235

**Closed by kevwan** 2020-12-08 14:42 UTC
